Some UI features
waterrmalann/kards pull request #13
Opened 2022-10-30 20:30 UTC by maliksenpai

- Added hover effect for icon buttons 
- Added shadow for sidebar
 - Added listen clickoutside for sidebar

2022-10-31 16:25 UTC, waterrmalann commented on css/main.css
> +    min-height: 95vh;
This seems to have a side effect of pushing the horizontal scrollbar too low that it's not visible at all.

For accessibility reasons, it's desirable to keep the scrollbar visible.

2022-10-31 16:33 UTC, waterrmalann commented on css/main.css
> +.fa {
Really love the hover effect.

It did seem to increase the size (height) of each individual cell of a card. I personally preferred the more compact cards like before but I like this too, perhaps an updated theme (which I plan to work on later) would make it look better.

2022-10-31 16:35 UTC, waterrmalann commented on js/main.js
> +    console.log("malik", 123);
I feel like you could get rid of this console log line here.

2022-10-31 16:36 UTC, waterrmalann reviewed
Really appreciate the pull request!

I'd love to merge some of these changes to the main branch. I've left some comments on some things, you could check it out and maybe fix those.

2022-10-31 19:05 UTC, maliksenpai commented
Hello @waterrmalann ,

Can you check again my pr?

2022-11-01 15:50 UTC, waterrmalann commented on css/main.css
> +    min-height: 93vh;
This still does not fix the issue of the invisible horizontal scrollbar on my device. I feel like the old percentage value of 85% would be most compatible for min-height instead.

2022-11-01 16:26 UTC, waterrmalann requested changes
One more change and I think it's good to merge :)

2022-11-01 19:02 UTC, maliksenpai commented
@waterrmalann I reverted min-height. Also is there anything to do after that?

2022-11-02 14:23 UTC, waterrmalann approved these changes

2022-11-02 14:49 UTC, waterrmalann commented
> @waterrmalann I reverted min-height. 

Nice work! All good now :)

> Also is there anything to do after that pr?

Not much else here but if you wish to help, you could check out the open [issues](https://github.com/waterrmalann/kards/issues).

2022-11-02 14:49 UTC, merged